FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /build

COPY ../pom.xml /build/pom.xml
COPY ../idm-proto /build/idm-proto
COPY ../client-service /build/client-service
COPY ../event-service /build/event-service
COPY ../idm-service /build/idm-service

RUN mvn -q -pl client-service -am clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=builder /build/client-service/target/client-service-*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
