FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /build

COPY ../pom.xml /build/pom.xml
COPY ../idm-proto /build/idm-proto
COPY ../idm-service /build/idm-service
COPY ../client-service /build/client-service
COPY ../event-service /build/event-service

RUN mvn -q -pl idm-service -am clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /build/idm-service/target/idm-service-*.jar app.jar

EXPOSE 9090

ENTRYPOINT ["java", "-jar", "app.jar"]
