FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /build

COPY ../pom.xml /build/pom.xml
COPY ../event-service /build/event-service
COPY ../client-service /build/client-service

RUN mvn -q -pl event-service -am clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=builder /build/event-service/target/event-service-*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
